# By Harsh H. Rajpurohit
name: vpn_basic_project
description: Flutter Android VPN based on OpenVPN Library.
publish_to: 'none'

# App Version
version: 1.0.3+3

environment:
  sdk: ^3.6.1

# App dependencies
dependencies:
  flutter:
    sdk: flutter

  # Getx for state management
  get: ^4.7.2

  get_storage: ^2.1.1

  # Cupertino style icons
  cupertino_icons: ^1.0.8
  flutter_rating_bar: ^4.0.1
  # For API Call
  http: ^1.3.0
  url_launcher: ^6.3.1
  cached_network_image: ^3.4.1
  # Converting CSV data to List
  csv: ^6.0.0
  # Icons
  # cupertino_icons: ^1.0.8
  iconsax: ^0.0.8
  # For Lottie Animation
  lottie: ^3.3.1
  logger: ^2.5.0
  #lottie: ^3.2.0
  connectivity_plus: ^5.0.1
  shimmer: ^3.0.0

  # For storing data (in local storage) 
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # For integrating ads
  google_mobile_ads: ^5.3.1
  # localization:
  easy_localization: ^3.0.0
  # For firebase
  #firebase_core: ^3.12.1
  #firebase_storage: ^12.3.7
  firebase_core: ^3.9.0 #^2.23.0
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.2.3

  # For Remote Config
  firebase_remote_config: ^5.4.2
  flutter_launcher_icons: ^0.14.4
  #flutter_launcher_icons: ^0.9.2
  geolocator: ^12.0.0 # Use latest version
  geocoding: ^3.0.0 # Use latest version
  #flutter build apk --no-tree-shake-icons
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Change package name  
  # change_app_package_name: ^1.1.0

  # Encourages good practices
  flutter_lints: ^5.0.0


flutter_icons:
  android: true
  ios: true
  image_path: "assets/playstore.png"  # path to your base icon image
  adaptive_icon_background: "#ffffff"  # for Android adaptive icons
  adaptive_icon_foreground: "assets/images/logo.png"
  #flutter pub run flutter_launcher_icons:main

flutter:
  # Enabling material design
  uses-material-design: true

  # App assets
  assets:
    - assets/
    - assets/vpn/
    - assets/images/
    - assets/lottie/
    - assets/flags/
    - assets/translations/