// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHjbzhDlFTyppLqQqk0GINsI1ockiFFrI',
    appId: '1:807584637430:android:935875eade8411a0ace7d7',
    messagingSenderId: '807584637430',
    projectId: 'mvpn-8d600',
    storageBucket: 'mvpn-8d600.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWza2VDbs3mORhSjXdYEFhBgnAY27cNa8',
    appId: '1:807584637430:web:17426280867a64a5ace7d7',
    messagingSenderId: '807584637430',
    projectId: 'mvpn-8d600',
    authDomain: 'mvpn-8d600.firebaseapp.com',
    storageBucket: 'mvpn-8d600.firebasestorage.app',
    measurementId: 'G-EXEPRXLR4Z',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcqcPcwbQUp8ClxyRWponqATZEFgoOlyI',
    appId: '1:807584637430:ios:f4c6e3e8ddaad2caace7d7',
    messagingSenderId: '807584637430',
    projectId: 'mvpn-8d600',
    storageBucket: 'mvpn-8d600.firebasestorage.app',
    iosBundleId: 'com.maitechno.mVpn',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcqcPcwbQUp8ClxyRWponqATZEFgoOlyI',
    appId: '1:807584637430:ios:f4c6e3e8ddaad2caace7d7',
    messagingSenderId: '807584637430',
    projectId: 'mvpn-8d600',
    storageBucket: 'mvpn-8d600.firebasestorage.app',
    iosBundleId: 'com.maitechno.mVpn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWza2VDbs3mORhSjXdYEFhBgnAY27cNa8',
    appId: '1:807584637430:web:6ec5b67bf55b2acdace7d7',
    messagingSenderId: '807584637430',
    projectId: 'mvpn-8d600',
    authDomain: 'mvpn-8d600.firebaseapp.com',
    storageBucket: 'mvpn-8d600.firebasestorage.app',
    measurementId: 'G-XGR8LRCNHH',
  );

}